spring.application.name=STOCK-SERVICE

server.port=${PORT:8088}

# ===============================
# DATABASE CONFIGURATION (MongoDB)
# ===============================
spring.data.mongodb.uri=mongodb+srv://admin:admin123@svacham.78asolj.mongodb.net/svacham_stock_db?retryWrites=true&w=majority&tls=true
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
spring.data.mongodb.ssl.enabled=true
# ===============================
# EUREKA CLIENT CONFIGURATION
# ===============================
eureka.client.service-url.defaultZone=https://svacham-admin-management.onrender.com/eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# ===============================
# CONFIG SERVER DISABLE
# ===============================
spring.cloud.config.enabled=false
spring.cloud.config.import-check.enabled=false

# ===============================
# LOGGING
# ===============================
logging.level.org.springframework.security=DEBUG
logging.level.com.svacham=DEBUG