spring.application.name=ORDER-SERVICE

server.port=${PORT:8085}

# =====================================
# MONGODB CONFIGURATION
# =====================================
spring.data.mongodb.uri=mongodb+srv://admin:admin123@svacham.78asolj.mongodb.net/svacham_order_db?retryWrites=true&w=majority&tls=true
spring.data.mongodb.auto-index-creation=true

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

# =====================================
# EUREKA CLIENT CONFIGURATION
# =====================================
eureka.client.service-url.defaultZone=https://svacham-admin-management.onrender.com/eureka/

eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true

# =====================================
# CONFIG SERVER DISABLE
# =====================================
spring.cloud.config.enabled=false
spring.cloud.config.import-check.enabled=false

# =====================================
# LOGGING
# =====================================
logging.level.org.springframework.security=DEBUG
logging.level.com.svacham.clientservice=DEBUG
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG