spring.application.name=ORDER-SERVICE

server.port=8085

# ===============================
# DATABASE CONFIGURATION
# ===============================

spring.data.mongodb.uri=mongodb+srv://admin:admin123@svacham.78asolj.mongodb.net/svacham_order_db?retryWrites=true&w=majority&appName=svacham
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

# ===============================
# EUREKA CLIENT CONFIGURATION
# ===============================

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true
# ===============================
# CONFIG SERVER DISABLE
# ===============================
spring.cloud.config.enabled=false

# ===============================
# LOGGING
# ===============================
logging.level.org.springframework.security=DEBUG
logging.level.com.svacham.clientservice=DEBUG

spring.cloud.config.import-check.enabled=false