# =====================================
# SERVER CONFIG
# =====================================
server.port=${PORT:8761}

  # =====================================
  # APPLICATION NAME
  # =====================================
spring.application.name=SERVICE-REGISTRY

  # =====================================
  # EUREKA CONFIG
  # =====================================
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false