spring.application.name=SPENDING-SERVICE

server.port=8087

# ===============================
# DATABASE CONFIGURATION
# ===============================
spring.datasource.url=jdbc:mysql://localhost:3306/svacham_spending_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=W7301@jqir#
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
# JPA / HIBERNATE CONFIGURATION
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# ===============================
# EUREKA CLIENT CONFIGURATION
# ===============================
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
# ===============================
# CONFIG SERVER DISABLE
# ===============================
spring.cloud.config.enabled=false

# ===============================
# LOGGING
# ===============================
logging.level.org.springframework.security=DEBUG
logging.level.com.svacham.clientservice=DEBUG

spring.cloud.config.import-check.enabled=false