spring.application.name=SPENDING-SERVICE

server.port=${PORT:8087}

# ===============================
# DATABASE CONFIGURATION
# ===============================
spring.data.mongodb.uri=mongodb+srv://admin:admin123@svacham.78asolj.mongodb.net/svacham_spending_db?retryWrites=true&w=majority&appName=svacham
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

# ===============================
# EUREKA CLIENT CONFIGURATION
# ===============================
eureka.client.service-url.defaultZone=https://svacham-admin-management.onrender.com/eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
# ===============================
# CONFIG SERVER DISABLE
# ===============================
spring.cloud.config.enabled=false

# ===============================
# LOGGING
# ===============================
logging.level.org.springframework.security=DEBUG
logging.level.com.svacham.clientservice=DEBUG

spring.cloud.config.import-check.enabled=false