server.port=${PORT:8081}

spring.application.name=AUTH-SERVICE

# =====================================
# MONGODB
# =====================================
spring.data.mongodb.uri=mongodb+srv://admin:admin123@svacham.78asolj.mongodb.net/svacham_auth_db?retryWrites=true&w=majority&tls=true
spring.data.mongodb.auto-index-creation=true

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

# =====================================
# EUREKA
# =====================================
eureka.client.service-url.defaultZone=https://svacham-admin-management.onrender.com/eureka/

eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# =====================================
# SPRING CLOUD CONFIG
# =====================================
spring.cloud.config.enabled=false
spring.cloud.config.import-check.enabled=false

# =====================================
# JWT
# =====================================
jwt.secret=svachamsecretkeysvachamsecretkeysvacham123456
jwt.expiration=86400000

# =====================================
# LOGGING
# =====================================
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG